# Site settings
title: Chris Coger
email: christopher.coger@gmail.com
url: https://coger.github.io
description: "Chris Coger's personal website."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3c5f87 #80B3FF
  secondary: b13533 #FD6E8A
  secondary-dark: 070f19 #A2122F

# Footer settings
footer:
  copyright: Christopher Coger
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/_Coger
  - title: facebook
    url: https://www.facebook.com/chris.coger
  - title: linkedin
    url: https://www.linkedin.com/in/christophercoger
  - title: google-plus
    url: https://plus.google.com/+ChristopherCoger/
  - title: github
    url: http://github.com/coger

# Postal address (add as many lines as necessary)
address:
  - line: '1300 South Arlington Ridge Rd, Apt 308'
  - line: 'Arlington, VA, 22202'

# Credits content
credits:
  - line: christopher.coger@gmail.com
  - line: (585) 770-4276

# Build settings
markdown: kramdown
permalink: pretty
